### PR TITLE
Handle nested parens

### PR DESCRIPTION
**Pull request by iko**
Some urls (for example [Graphite](http://graphite.readthedocs.org/en/1.0/url-api.html)) have some nested parens in the parameters. An url with nested parens would miss the last closing paren and the linkified result would look something like this:

[http://example.com/render?target=summarize(deriviative(app.numUsers),%221min%22](http://example.com/render?target=summarize(deriviative(app.numUsers),%221min%22)&title=New_Users_Per_Minute))&title=New_Users_Per_Minute

I do realize that this fix will allow unbalanced parens. Is that a problem?

### CODE REVIEW

**Comment by puzrin** [comment]
Example is acceptable, but i don't like implementation. It will ignore all intermetiate conditions between 2 scopen groups:

`(foo)ignored---content(bar)`

**Comment by iko** [comment]
Aha! Didn't catch that. I'll work on another way of doing this. Thanks.

**Comment by puzrin** [comment]
@iko, honestly, i'm not sure this task can be solved without side effects like reDoS.

How critical is it to detect such links properly?

**Comment by iko** [comment]
How about limiting the nesting? [Twitter-text](https://github.com/twitter/twitter-text/blob/master/js/twitter-text.js#L242) for example has a hard limit of one level. I haven't had the time to look into this yet, though.

Detecting urls with nested parens is not the most critical feature at the moment, but eventually we'll probably need it to work.

**Comment by puzrin** [comment]
Idea looks nice.

**Comment by batmat** [comment]
Hi guys, another example of complex/long url that the parser is unable to grok:

     http://sv-t-vnl-forge-metrics:5601/?#/dashboard/Logs-Marmotte?_a=(filters:!(),panels:!((col:1,columns:!(message,host,tags),id:Marmotte-logs,row:1,size_x:12,size_y:8,sort:!('@timestamp',asc),type:search)),query:(query_string:(analyze_wildcard:!t,query:'*')),title:'Logs%20Marmotte')&_g=(refreshInterval:(display:'10%20seconds',pause:!f,section:1,value:10000),time:(from:now-15m,mode:quick,to:now))

FYI, this URL is one generated by the "share" link of Kibana 4.

**Comment by puzrin** [comment]
I summarized all in #23 for better tracking. May be worth to close PR if no updates expected soon.

**Pull request closed without merging**
