### PR TITLE
Allow dash at the end of url

### LINKED ISSUE #20: Trailing "-" not included in linkified url
It seems that some websites can have trailing `-` in their urls, which don't get included in the linkified url, thus breaking the link.

Example url:
http://www.bloomberg.com/news/articles/2015-06-26/from-deutsche-bank-to-siemens-what-s-troubling-germany-inc-

I understand that this might be a controversial topic, but I still feel that a `-` at the end of an url is a more usual case than having a `-` by mistake at the end like a period or a comma.

I could take a stab at getting a pr in for this if this sounds like a good change.

### PR DESCRIPTION
**Pull request by Mumakil**
Fixes #20.

### CODE REVIEW

**Comment by puzrin** [comment]
I've finished review. See 2 comments.

**Comment by Mumakil** [comment]
Thanks, should be fixed now.

**Comment by puzrin** [comment]
LGTM. Please, squash into single commit, and i'll merge it.

**Comment by puzrin** [comment]
Published. Do you use it separately or need fast markdown-it update too?

**Comment by Mumakil** [comment]
Markdown-it update would be nice as we use the bundled linkify-it.

Thank you!

**Pull request merged**
