### PR TITLE
Use https for urls without scheme

### PR DESCRIPTION
**Pull request by f0x52**
Maybe make this configurable later on

### CODE REVIEW

**Comment by puzrin** [comment]
No resons to change defaults. Just override normalizer, it's specially done for such things.

**Comment by mvanroon** [comment]
I agree that https should be the standard

**Comment by Nic0S** [comment]
Sorry to revive an old thread, but is it possible to override the normalizer without also overriding the validator?

**Comment by kyle-go** [comment]
watching~~~

**Pull request closed without merging**
